import type { PylonCookieAttributes } from "./cookie-settings.js";
import type { PylonEncKey, PylonSignKey } from "./keys.js";

/**
 * Session SETTINGS — the `new Pylon({ auth: { session } })` declaration. A pylon
 * session IS a cookie, so this carries the same presentation defaults and the
 * same two FLAT key selectors as `PylonCookieSettings`
 * (`signature`/`encryption`).
 *
 * `signature` defaults to the cookie one — `auth.session.signature ??
 * cookies.signature` (see `resolveSessionKeys`) — so naming `cookies` alone signs
 * session cookies too, and naming `auth.session.signature` gives them their own
 * key. Verification is derived from the resolved `signature` condition, never
 * declared.
 *
 * `encryption` does NOT inherit. It is REQUIRED here and declared here, because
 * the two roles are not symmetric: an absent `signature` means signing is off,
 * which is a deployment's to choose, while an absent `encryption` is not a choice
 * a session can make in either mode. Making it required is what lets the compiler
 * refuse the state instead of a boot check reporting it.
 *
 * The `Session` entity lives in the AUTHORITATIVE `kv` source, never in `cache`:
 * evicting a session logs the user out. With no `kv` source the session is
 * cookie-only — the whole session object travels in the cookie.
 *
 * With a `kv` source the cookie carries `{ id, sec }`: the row's name, and a
 * per-session secret that HKDF-derives the key sealing the row's token set and
 * scope. Pylon keeps no copy of `sec`, so a kv dump is inert — and the decrypt is
 * the authentication, no digest is stored and none is compared. The secret is
 * minted with the session id and does NOT rotate on refresh. There is no flag:
 * this is the only mode for a kv-backed session.
 *
 * ⚠ `enabled` is the literal `true`, not a boolean. A present block that does
 * nothing is a trap: `{ enabled: false }` reads as configured-and-off while the
 * middleware is simply never mounted. Presence IS the intent — omit the block to
 * turn sessions off.
 *
 * ⚠ `encryption`'s job is the COOKIE alone. Cookie-only, the cookie IS the token
 * set. Kv-backed, the cookie holds `sec` — the key that opens the stored session —
 * and an unsealed cookie puts that key in the browser jar and in every log that
 * dumps `Cookie` headers. The at-rest seal takes no configuration: it is the
 * holder's key, derived per session, with no server key to rotate or lose.
 *
 * ⚠ Four cookie attributes are DELIBERATELY absent, because none of them is the
 * deployment's to choose:
 *
 * - **`name`** — always `pylon_session`. Two of pylon's three cookie names
 *   (`pylon_login_session`, `pylon_logout_session`) were never configurable, and
 *   the collision case that would justify a configurable name — two pylons on one
 *   domain — is not solved by making one of the three configurable.
 * - **`httpOnly`** — always `true`. The cookie addresses an access token, an id
 *   token and a refresh token; `httpOnly: false` hands all three to any XSS.
 * - **`encoding`** — the value is a store id or a sealed blob, both generated by
 *   pylon. How pylon encodes its own opaque handle is not a deployment concern.
 * - **`expiry`** — the cookie's expiry IS `session.expiresAt`, derived at
 *   set-time. A separately configured max-age can only disagree with the record:
 *   a cookie outliving it points at nothing, a record outliving the cookie is
 *   unreachable. `expiresAt: null` ⇒ no expiry attribute ⇒ a browser-session
 *   cookie.
 */
export type PylonSessionSettings = Pick<
  PylonCookieAttributes,
  "domain" | "path" | "priority" | "sameSite" | "secure"
> & {
  enabled: true;
  encryption: PylonEncKey;
  signature?: PylonSignKey;
};
