import type { PylonCookieAttributes } from "./cookie-settings.js";
import type { PylonEncKey, PylonSignKey } from "./keys.js";

/**
 * Session SETTINGS — the `new Pylon({ auth: { session } })` declaration. A pylon
 * session IS a cookie, so this carries the same presentation defaults and the
 * same two FLAT key selectors as `PylonCookieSettings`
 * (`signature`/`encryption`).
 *
 * Each key selector defaults to the cookie one:
 * `auth.session.<role> ?? cookies.<role>` (see `resolveSessionKeys`). Name only
 * `cookies` and one set of keys does everything; name `auth.session` keys too and
 * the session cookie is signed / sealed with its OWN key. Verification is derived
 * from the resolved `signature` condition, never declared.
 *
 * The `Session` entity lives in the AUTHORITATIVE `kv` source, never in `cache`:
 * evicting a session logs the user out. With no `kv` source the session is
 * cookie-only — the whole session object travels in the cookie.
 *
 * ⚠ `enabled` is the literal `true`, not a boolean. A present block that does
 * nothing is a trap: `{ enabled: false }` reads as configured-and-off while the
 * middleware is simply never mounted. Presence IS the intent — omit the block to
 * turn sessions off.
 *
 * ⚠ `encryption` — resolved as `auth.session.encryption ?? cookies.encryption` —
 * is REQUIRED for a COOKIE-ONLY session and merely recommended for a `kv`-backed
 * one, and the difference is what the cookie holds. With a `kv` source the cookie
 * carries an opaque store id and the tokens sit at rest behind that store's
 * access boundary; with none, the WHOLE session object — access token, id token,
 * refresh token — is what goes into the cookie, base64url ENCODED rather than
 * encrypted, and is re-sent on every request. So a cookie-only session with no
 * key resolvable is a boot failure (`session_encryption_not_configured`), and a
 * kv-backed one warns once and runs. See `validateSessionEncryption`.
 *
 * ⚠ Four cookie attributes are DELIBERATELY absent, because none of them is the
 * deployment's to choose:
 *
 * - **`name`** — always `pylon_session`. Two of pylon's three cookie names
 *   (`pylon_login_session`, `pylon_logout_session`) were never configurable, and
 *   the collision case that would justify a configurable name — two pylons on one
 *   domain — is not solved by making one of the three configurable.
 * - **`httpOnly`** — always `true`. The cookie addresses an access token, an id
 *   token and a refresh token; `httpOnly: false` hands all three to any XSS.
 * - **`encoding`** — the value is a store id or a sealed blob, both generated by
 *   pylon. How pylon encodes its own opaque handle is not a deployment concern.
 * - **`expiry`** — the cookie's expiry IS `session.expiresAt`, derived at
 *   set-time. A separately configured max-age can only disagree with the record:
 *   a cookie outliving it points at nothing, a record outliving the cookie is
 *   unreachable. `expiresAt: null` ⇒ no expiry attribute ⇒ a browser-session
 *   cookie.
 */
export type PylonSessionSettings = Pick<
  PylonCookieAttributes,
  "domain" | "path" | "priority" | "sameSite" | "secure"
> & {
  enabled: true;
  encryption?: PylonEncKey;
  signature?: PylonSignKey;
};
