import type { GeneratedDecoratorOptions } from "#internal/entity/types/decorators";
import type { MetaGeneratedStrategy } from "#internal/entity/types/metadata";
import { stageGenerated } from "#internal/entity/metadata/stage-metadata";

/**
 * Mark a field as auto-generated by the ORM or database.
 *
 * - `@Generated("uuid")` — generate a UUID v4 on insert
 * - `@Generated("increment")` — use a database auto-increment sequence
 * - `@Generated("string", { length: 12 })` — generate a random string with custom length
 */
export const Generated =
  (strategy: MetaGeneratedStrategy, options: GeneratedDecoratorOptions = {}) =>
  (_target: undefined, context: ClassFieldDecoratorContext): void => {
    stageGenerated(context.metadata, {
      key: String(context.name),
      strategy,
      length: options.length ?? null,
      max: options.max ?? null,
      min: options.min ?? null,
    });
  };
