import type { IrisEnvelope } from "../../../types/iris-envelope.js";

export const serializeStreamFields = (envelope: IrisEnvelope): Array<string> => {
  return [
    "payload",
    envelope.payload.toString("base64"),
    "headers",
    JSON.stringify(envelope.headers),
    "topic",
    envelope.topic,
    "attempt",
    String(envelope.attempt),
    "maxRetries",
    String(envelope.maxRetries),
    "retryStrategy",
    envelope.retryStrategy,
    "retryDelay",
    String(envelope.retryDelay),
    "retryDelayMax",
    String(envelope.retryDelayMax),
    "retryMultiplier",
    String(envelope.retryMultiplier),
    "retryJitter",
    String(envelope.retryJitter),
    "priority",
    String(envelope.priority),
    "timestamp",
    String(envelope.timestamp),
    "expiry",
    envelope.expiry !== null ? String(envelope.expiry) : "",
    "broadcast",
    String(envelope.broadcast),
    "replyTo",
    envelope.replyTo ?? "",
    "correlationId",
    envelope.correlationId ?? "",
    "identifierValue",
    envelope.identifierValue ?? "",
  ];
};
