version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  authentication_service:
    image: lindorm-io/authentication-service
    container_name: authentication_service
    links:
      - mongo:mongo
      - redis:redis
      - communication_service:communication-service
      - device_service:device-service
      - federation_service:federation-service
      - identity_service:identity-service
      - oauth_service:oauth-service
      - vault_service:vault-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/authentication-service:/app/volumes/config

  communication_service:
    image: lindorm-io/communication-service
    container_name: communication_service
    links:
      - mongo:mongo
      - redis:redis
      - device_service:device-service
      - oauth_service:oauth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/communication-service:/app/volumes/config

  device_service:
    image: lindorm-io/device-service
    container_name: device_service
    links:
      - mongo:mongo
      - redis:redis
      - communication_service:communication-service
      - oauth_service:oauth-service
      - vault_service:vault-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/device-service:/app/volumes/config

  identity_service:
    image: lindorm-io/identity-service
    container_name: identity_service
    links:
      - mongo:mongo
      - redis:redis
      - communication_service:communication-service
      - oauth_service:oauth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/identity-service:/app/volumes/config

  oauth_service:
    image: lindorm-io/oauth-service
    container_name: oauth_service
    links:
      - mongo:mongo
      - redis:redis
      - authentication_service:authentication-service
      - identity_service:identity-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/oauth-service:/app/volumes/config

  federation_service:
    image: lindorm-io/federation-service
    container_name: federation_service
    links:
      - mongo:mongo
      - redis:redis
      - identity_service:identity-service
      - oauth_service:oauth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/federation-service:/app/volumes/config

  vault_service:
    image: lindorm-io/vault-service
    container_name: vault_service
    links:
      - mongo:mongo
      - redis:redis
      - oauth_service:oauth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_CONFIG_DIR=/config:/volumes/config
      - NODE_CONFIG_ENV=example
      - NODE_ENV=development
    volumes:
      - ./config/vault-service:/app/volumes/config
