version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_Vi14uVKC
    ports:
      - "5006:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  redis:
    image: redis
    restart: always
    container_name: redis_Vi14uVKC
    ports:
      - "5005:6379"
