version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    container_name: koa_keystore_mongo
    labels:
      - mongo
    ports:
      - "27016:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  redis:
    image: redis
    restart: always
    container_name: koa_keystore_redis
    labels:
      - redis
    ports:
      - "6378:6379"
