version: "3.7"

services:
  service_device_mongo:
    image: mongo
    restart: always
    container_name: service_device_mongo
    labels:
      - mongo
    ports:
      - "3201:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  service_device_redis:
    image: redis
    restart: always
    container_name: service_device_redis
    labels:
      - redis
    ports:
      - "3202:6379"
