version: "3.7"

services:
  device_service_mongo:
    image: mongo
    container_name: device_service_mongo
    labels:
      - mongo
    ports:
      - "3301:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  device_service_redis:
    image: redis
    container_name: device_service_redis
    labels:
      - redis
    ports:
      - "3302:6379"
