mongo:
  host: localhost
  port: 3301
  db_name: device
  username: root
  password: example

oauth:
  client_id: 8da48653-ba29-416e-b882-393b60dce178
  client_secret: X4P2a8llWDVJbtzRAVnHObcLyOMAe2vYa2GAs2kSNXonlRcWblDYU07bJxC20B8Co2PJKpTITUBs2hEOV90Vr4o5zKhYme067RortdPmGoVpa6neHqNDZGIF1YXVcp36

redis:
  host: localhost
  port: 3302

server:
  domain: https://development.lindorm.io
  environment: development
  host: http://localhost
  issuer: https://device.development.lindorm.io
  port: 3300
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://localhost
    port: 3200
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3500
  vault_service:
    issuer: https://vault.development.lindorm.io
    host: http://localhost
    port: 3600
