logger:
  level: debug
  colours: true
  readable: true
  timestamp: true

oauth:
  client_id: 8da48653-ba29-416e-b882-393b60dce178
  client_secret: siKP6qVeEoBxTOPV4Q4Ijiy6laUhgKXaZfrSYWJKBm3IfiO04fie7KIeFJdIbFUJ

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://device.development.lindorm.io
  host: http://localhost
  port: 3300
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://localhost
    port: 3200
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3500
  vault_service:
    issuer: https://vault.development.lindorm.io
    host: http://localhost
    port: 3700
