redis:
  username: username
  password: password

server:
  domain: https://lindorm.io
  environment: production
  host: https://device.lindorm.io

services:
  communication_service:
    host: https://communication.lindorm.io
  oauth_service:
    host: https://oauth.lindorm.io
