oauth:
  host: https://oauth.stage.api.lindorm.io

redis:
  username: username
  password: password

server:
  environment: staging
  host: https://device.stage.api.lindorm.io

services:
  communication_service: https://communication.stage.api.lindorm.io
