redis:
  username: username
  password: password

server:
  domain: https://staging.lindorm.io
  environment: staging
  issuer: https://device.staging.lindorm.io
  host: https://device.staging.lindorm.io

services:
  communication_service:
    host: https://communication.staging.lindorm.io
  oauth_service:
    host: https://oauth.staging.lindorm.io
