mongo:
  host: localhost
  port: 3301
  db_name: device
  username: root
  password: example

oauth:
  client_id: secret
  client_secret: secret

redis:
  host: localhost
  port: 3302

server:
  domain: https://test.lindorm.io
  environment: test
  host: https://device.test.lindorm.io
  port: 3300

services:
  communication_service:
    host: https://communication.test.lindorm.io
  oauth_service:
    host: https://oauth.test.lindorm.io
