crypto:
  aes: secret
  sha: secret

mongo:
  host: localhost
  port: 3201
  db_name: device
  username: root
  password: example

oauth:
  host: https://oauth.test.api.lindorm.io
  client_id: secret
  client_secret: secret

redis:
  host: localhost
  port: 3202
  username: null
  password: null

server:
  environment: test
  host: https://device.test.api.lindorm.io
  port: 3200

services:
  communication_service: https://communication.test.api.lindorm.io
