logger:
  level: silly
  colours: false
  readable: false
  timestamp: true

mongo:
  host: localhost
  port: 27017
  db_name: vault_db
  username: root
  password: example

oauth:
  client_id: id
  client_secret: secret

redis:
  host: localhost
  port: 6379
  namespace: vault_service

secrets:
  aes: jN8dLU1CHf9bO1iAF76NTx8yR8h57TWX

server:
  domain: https://lindorm.io
  environment: development
  issuer: https://vault.lindorm.io
  host: http://localhost
  keys: []
  port: 3000
  workers: false

services:
  oauth_service:
    client_name: oauthClient
    issuer: https://oauth.lindorm.io
    host: http://localhost
