logger:
  level: debug
  colours: true
  readable: true
  timestamp: true

oauth:
  client_id: c233687a-c610-412c-985b-5f6e95fbf47d
  client_secret: oRGyqy9VzNFrZKLXs5VV5Gl8gLLXYI4QcLUfO6oEDz7VUMaCwY6srKnqUHha7jha

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://vault.development.lindorm.io
  host: http://localhost
  port: 3007
  workers: true

services:
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3005
