redis:
  username: username
  password: password

server:
  domain: https://lindorm.io
  issuer: https://vault.lindorm.io
  host: https://vault.lindorm.io
  workers: true

services:
  oauth_service:
    host: https://oauth.lindorm.io
