mongo:
  host: localhost
  port: 3701
  username: root
  password: example

oauth:
  client_id: id
  client_secret: secret

redis:
  host: localhost
  port: 3702

server:
  domain: https://test.lindorm.io
  issuer: https://vault.test.lindorm.io
  host: https://vault.test.lindorm.io
  port: 3700
  workers: false

services:
  oauth_service:
    host: https://oauth.test.lindorm.io
