import type { AbortError } from "@lindorm/errors";
import { toAbortError as toSharedAbortError } from "../../../utils/abort.js";

/**
 * mysql errno for `Query execution was interrupted`. Emitted when a running
 * query is interrupted by a `KILL QUERY <thread-id>` on another session.
 * See: https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_query_interrupted
 */
export const MYSQL_QUERY_INTERRUPTED_ERRNO = 1317;

export const toAbortError = (reason: unknown, cause?: unknown): AbortError =>
  toSharedAbortError(reason, cause, "MySQL query cancelled");

export const isMysqlQueryInterruptedError = (err: unknown): boolean =>
  typeof err === "object" &&
  err !== null &&
  (err as { errno?: unknown }).errno === MYSQL_QUERY_INTERRUPTED_ERRNO;

/**
 * Prefix allowlist for MySQL transaction-boundary statements that must never
 * be gated by a post-success `signal.aborted` check. Gating these would cause
 * the caller's ROLLBACK / RELEASE SAVEPOINT / COMMIT to throw after an abort,
 * leaving the PoolConnection in an aborted-tx state and poisoning the pool.
 *
 * User queries dispatched through the tx-scoped client do NOT start with any
 * of these prefixes — even a case-insensitive UPDATE/SELECT/DELETE/INSERT
 * does not collide with SAVEPOINT / ROLLBACK / COMMIT / START TRANSACTION /
 * SET TRANSACTION / RELEASE SAVEPOINT.
 */
const TX_BOUNDARY_PREFIXES = [
  "START TRANSACTION",
  "COMMIT",
  "ROLLBACK", // covers "ROLLBACK" and "ROLLBACK TO SAVEPOINT ..."
  "SAVEPOINT",
  "RELEASE SAVEPOINT",
  "SET TRANSACTION",
];

export const isTxBoundaryStatement = (sql: string): boolean => {
  // Statements are generated by proteus internals — never leading whitespace,
  // but be defensive.
  const normalised = sql.trimStart().toUpperCase();
  return TX_BOUNDARY_PREFIXES.some((prefix) => normalised.startsWith(prefix));
};
