services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    platform: linux/amd64
    ports:
      - "9200:9200"
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    mem_limit: 2147483648
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [ "CMD-SHELL", "curl -s https://localhost:9200" ]
      interval: 5s
      timeout: 30s
      retries: 120
