defaults:
  clients:
    active_state: false
    level_of_assurance: 1
    opaque_access_tokens: true
    opaque_refresh_tokens: true
  expiry:
    access_token: 3 minutes
    authorization_session: 30 minutes
    browser_session_remember: 30 days
    browser_session: 20 hours
    claims_session: 90 seconds
    client_credentials: 60 seconds
    code_session: 60 seconds
    elevation_session: 30 minutes
    id_token: 24 hours
    logout_session: 60 seconds
    refresh_token: 30 days
  sessions:
    loa_1_max_days: 90
    loa_2_max_days: 30
    loa_3_max_days: 3
    loa_4_max_minutes: 15
  tenants:
    active_state: false

frontend:
  host: localhost
  routes:
    error: /error

logger:
  level: info
  colours: false
  readable: false
  timestamp: true

mongo:
  host: localhost
  port: 27017
  db_name: oauth_db
  username: root
  password: example

oauth:
  client_id: id

redirect:
  claims: /admin/claims
  consent: /oauth/consent
  elevate: /oauth/elevate
  login: /oauth/login
  logout: /oauth/logout
  select: /oauth/select
  userinfo: /userinfo

redis:
  host: localhost
  port: 6379
  namespace: oauth_service

server:
  domain: https://lindorm.io
  environment: development
  issuer: https://oauth.lindorm.io
  host: http://localhost
  keys: []
  port: 3000
  workers: false

services:
  authentication_service:
    client_name: authenticationClient
    issuer: https://authentication.lindorm.io
    host: localhost
  identity_service:
    client_name: identityClient
    issuer: https://identity.lindorm.io
    host: localhost
