defaults:
  client_active_state: false
  tenant_active_state: false
  level_of_assurance: 1
  access_token_expiry: 3 minutes
  authorization_session_expiry: 30 minutes
  browser_session_expiry: 20 hours
  browser_session_remember_expiry: 30 days
  client_credentials_expiry: 60 seconds
  code_session_expiry: 60 seconds
  id_token_expiry: 24 hours
  logout_session_expiry: 60 seconds
  refresh_session_expiry: 30 days

frontend:
  host: localhost
  routes:
    error: /error

mongo:
  host: localhost
  port: 27017
  db_name: oauth
  username: username
  password: password

oauth:
  client_id: id

redirect:
  login: /oauth/login
  consent: /oauth/consent
  logout: /oauth/logout

redis:
  host: localhost
  port: 6379
  username: username

server:
  domain: https://lindorm.io
  environment: development
  host: http://localhost
  issuer: https://oauth.lindorm.io
  keys: []
  port: 3000
  workers: false

services:
  authentication_service:
    client_name: authenticationClient
    issuer: https://authentication.lindorm.io
    host: localhost
  identity_service:
    client_name: identityClient
    issuer: https://identity.lindorm.io
    host: localhost
