frontend:
  host: http://localhost
  port: 4500

logger:
  level: debug
  colours: true
  readable: true
  timestamp: true

oauth:
  client_id: 6e4d37bf-6121-4851-9229-52ea6530a297

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://oauth.development.lindorm.io
  host: http://localhost
  keys:
    - secret
  port: 3005
  workers: true

services:
  authentication_service:
    client_id: f39e83c0-10d8-49a1-8ecb-bb89f1d57b7f
    issuer: https://authentication.development.lindorm.io
    host: http://localhost
    port: 3001
  identity_service:
    client_id: 9993fa84-bedf-4a93-a421-1f63719cd9d3
    issuer: https://identity.development.lindorm.io
    host: http://localhost
    port: 3004
