cookies:
  keys:
    - secret

frontend:
  base_url: http://localhost:4000

mongo:
  host: localhost
  port: 3501
  db_name: oauth
  username: root
  password: example

oauth:
  client_id: secret

redis:
  host: localhost
  port: 3502

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://oauth.development.lindorm.io
  host: http://localhost
  port: 3500

services:
  authentication_service:
    issuer: https://authentication.development.lindorm.io
    host: http://localhost
    port: 3100
  identity_service:
    issuer: https://identity.development.lindorm.io
    host: http://localhost
    port: 3300
