server:
  domain: https://lindorm.io
  environment: production
  issuer: https://oauth.lindorm.io
  host: https://oauth.lindorm.io
  workers: true

redis:
  username: username
  password: password

services:
  authentication_service:
    host: https://authentication.lindorm.io
  identity_service:
    host: https://identity.lindorm.io
