server:
  domain: https://staging.lindorm.io
  environment: staging
  issuer: https://oauth.staging.lindorm.io
  host: https://oauth.staging.lindorm.io
  workers: true

redis:
  username: username
  password: password

services:
  authentication_service:
    host: https://authentication.staging.lindorm.io
  identity_service:
    host: https://identity.staging.lindorm.io
