frontend:
  host: https://frontend.url/

logger:
  level: error
  colours: true
  readable: true
  timestamp: true

mongo:
  host: localhost
  port: 27017
  username: root
  password: example

oauth:
  client_id: 6ea68f3d-e31e-4882-85a5-0a617f431fdd

redis:
  host: localhost
  port: 6379

server:
  domain: https://test.lindorm.io
  environment: test
  issuer: https://oauth.test.lindorm.io
  host: https://oauth.test.lindorm.io
  keys:
    - secret
  port: 3005
  workers: false

services:
  authentication_service:
    client_id: f39e83c0-10d8-49a1-8ecb-bb89f1d57b7f
    host: https://authentication.test.lindorm.io
  identity_service:
    client_id: 9993fa84-bedf-4a93-a421-1f63719cd9d3
    host: https://identity.test.lindorm.io
