logger:
  level: info
  colours: false
  readable: false
  timestamp: true

oauth:
  client_id: id
  client_secret: secret

redis:
  host: localhost
  port: 6379
  namespace: communication_service

server:
  domain: https://lindorm.io
  environment: development
  issuer: https://communication.lindorm.io
  host: http://localhost
  keys: []
  port: 3000
  workers: false

services:
  device_service:
    client_name: deviceClient
    issuer: https://device.lindorm.io
    host: http://localhost
  oauth_service:
    client_name: oauthClient
    issuer: https://oauth.lindorm.io
    host: http://localhost
