oauth:
  client_id: id
  client_secret: secret

redis:
  host: localhost
  port: 6379
  username: username

server:
  domain: https://lindorm.io
  environment: development
  issuer: https://communication.lindorm.io
  host: http://localhost
  port: 3000

services:
  device_service:
    issuer: https://device.lindorm.io
    host: http://localhost
  oauth_service:
    issuer: https://oauth.lindorm.io
    host: http://localhost
