logger:
  level: debug
  colours: true
  readable: true
  timestamp: true

oauth:
  client_id: aec0a293-4371-450a-bcfa-0f60f1f51a65
  client_secret: 2pBUdV9qyAEh1efe_8sMZUFXw2HPDkct9209UWVLSloY-Rt9fzn_N2wjKbAy-MOX

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://communication.development.lindorm.io
  host: http://localhost
  port: 3002
  workers: true

services:
  device_service:
    issuer: https://device.development.lindorm.io
    host: http://localhost
    port: 3003
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3005
