oauth:
  client_id: secret
  client_secret: secret

redis:
  host: localhost
  port: 3202

server:
  domain: https://development.lindorm.io
  environment: development
  host: http://localhost
  issuer: https://communication.development.lindorm.io
  port: 3200
  workers: true

services:
  device_service:
    issuer: https://device.development.lindorm.io
    host: http://localhost
    port: 3300
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3500
