redis:
  username: username
  password: password

server:
  domain: https://lindorm.io
  environment: production
  issuer: https://communication.lindorm.io
  host: https://communication.lindorm.io
  workers: true

services:
  device_service:
    host: https://device.lindorm.io
  oauth_service:
    host: https://oauth.lindorm.io
