redis:
  username: username
  password: password

server:
  domain: https://staging.lindorm.io
  environment: staging
  host: https://communication.staging.lindorm.io
  issuer: https://communication.staging.lindorm.io
  workers: true

services:
  device_service:
    host: https://device.staging.lindorm.io
  oauth_service:
    host: https://oauth.staging.lindorm.io
