logger:
  level: error
  colours: true
  readable: true
  timestamp: true

oauth:
  client_id: 6ea68f3d-e31e-4882-85a5-0a617f431fdd
  client_secret: secret

redis:
  host: localhost
  port: 6379

server:
  domain: https://test.lindorm.io
  environment: test
  issuer: https://communication.test.lindorm.io
  host: https://communication.test.lindorm.io
  port: 3002
  workers: false

services:
  device_service:
    host: https://device.test.lindorm.io
  oauth_service:
    host: https://oauth.test.lindorm.io
