oauth:
  client_id: secret
  client_secret: secret

redis:
  host: localhost
  port: 3202

server:
  domain: https://test.lindorm.io
  environment: test
  issuer: https://communication.test.lindorm.io
  host: https://communication.test.lindorm.io
  port: 3200

services:
  device_service:
    host: https://device.test.lindorm.io
  oauth_service:
    host: https://oauth.test.lindorm.io
