export enum AuthenticationStrategy {
  BANK_ID_SE = "urn:lindorm:auth:strategy:bank-id-se",
  DEVICE_CHALLENGE = "urn:lindorm:auth:strategy:device-challenge",
  EMAIL_CODE = "urn:lindorm:auth:strategy:email-code",
  EMAIL_OTP = "urn:lindorm:auth:strategy:email-otp",
  MFA_COOKIE = "urn:lindorm:auth:strategy:mfa-cookie",
  PASSWORD = "urn:lindorm:auth:strategy:password",
  PASSWORD_BROWSER_LINK = "urn:lindorm:auth:strategy:password-browser-link",
  PHONE_CODE = "urn:lindorm:auth:strategy:phone-code",
  PHONE_OTP = "urn:lindorm:auth:strategy:phone-otp",
  RDC_PUSH_NOTIFICATION = "urn:lindorm:auth:strategy:rdc-push-notification",
  RDC_QR_CODE = "urn:lindorm:auth:strategy:rdc-qr-code",
  RECOVERY_CODE = "urn:lindorm:auth:strategy:recovery-code",
  SESSION_DISPLAY_CODE = "urn:lindorm:auth:strategy:session-display-code",
  SESSION_OTP = "urn:lindorm:auth:strategy:session-otp",
  SESSION_QR_CODE = "urn:lindorm:auth:strategy:session-qr-code",
  TIME_BASED_OTP = "urn:lindorm:auth:strategy:time-based-otp",
  WEBAUTHN = "urn:lindorm:auth:strategy:webauthn",
}
