export enum ClientScope {
  AUTHORIZATION_READ = "authorization_read",
  AUTHORIZATION_WRITE = "authorization_write",
  CLIENT_DELETE = "client_delete",
  CLIENT_READ = "client_read",
  CLIENT_WRITE = "client_write",
  COMMUNICATION_EMIT = "communication_emit",
  COMMUNICATION_SEND = "communication_send",
  IDENTIFIER_READ = "identifier_read",
  IDENTIFIER_WRITE = "identifier_write",
  IDENTITY_READ = "identity_read",
  IDENTITY_WRITE = "identity_write",
  LOGOUT_READ = "logout_read",
  LOGOUT_WRITE = "logout_write",
  RDC_READ = "rdc_read",
  RDC_WRITE = "rdc_write",
}
