/**
 * The IANA "CoAP Content-Formats" registry: each ID that names one assigned media
 * type with no content coding, mapped to the registry's `Content Type` verbatim,
 * less the trailing `(TEMPORARY - …)` note IANA writes into the cell of a
 * provisional registration — a note on the registration, not part of the media
 * type. pinned: `coap-content-formats.test.ts`, against the committed snapshot.
 *
 * ⚠ A row with a content coding (`deflate`, `zstd`) stays out, so its ID is
 * refused: aegis cannot undo the coding, and the bare media type would hand
 * compressed bytes to a JSON, CBOR or text reader.
 */
export const COAP_CONTENT_FORMATS: Readonly<Record<number, string>> = {
  0: "text/plain; charset=utf-8",
  16: 'application/cose; cose-type="cose-encrypt0"',
  17: 'application/cose; cose-type="cose-mac0"',
  18: 'application/cose; cose-type="cose-sign1"',
  19: "application/ace+cbor",
  21: "image/gif",
  22: "image/jpeg",
  23: "image/png",
  40: "application/link-format",
  41: "application/xml",
  42: "application/octet-stream",
  47: "application/exi",
  50: "application/json",
  51: "application/json-patch+json",
  52: "application/merge-patch+json",
  60: "application/cbor",
  61: "application/cwt",
  62: "application/multipart-core",
  63: "application/cbor-seq",
  64: "application/edhoc+cbor-seq",
  65: "application/cid-edhoc+cbor-seq",
  96: 'application/cose; cose-type="cose-encrypt"',
  97: 'application/cose; cose-type="cose-mac"',
  98: 'application/cose; cose-type="cose-sign"',
  101: "application/cose-key",
  102: "application/cose-key-set",
  110: "application/senml+json",
  111: "application/sensml+json",
  112: "application/senml+cbor",
  113: "application/sensml+cbor",
  114: "application/senml-exi",
  115: "application/sensml-exi",
  140: "application/yang-data+cbor; id=sid",
  256: "application/coap-group+json",
  257: "application/concise-problem-details+cbor",
  258: "application/swid+cbor",
  259: "application/pkixcmp",
  260: "application/yang-sid+json",
  261: "application/ace-groupcomm+cbor",
  262: "application/ace-trl+cbor",
  263: "application/eat+cwt",
  264: "application/eat+jwt",
  265: "application/eat-bun+cbor",
  266: "application/eat-bun+json",
  267: "application/eat-ucs+cbor",
  268: "application/eat-ucs+json",
  269: "application/coap-eap",
  270: "application/suit-report+cose",
  271: "application/dots+cbor",
  272: "application/missing-blocks+cbor-seq",
  273: "application/cmw+cbor",
  274: "application/cmw+json",
  275: "application/cmw+cose",
  276: "application/cmw+jws",
  277: "application/scitt-statement+cose",
  278: "application/scitt-receipt+cose",
  279: "application/statuslist+cwt",
  280: "application/pkcs7-mime; smime-type=server-generated-key",
  281: "application/pkcs7-mime; smime-type=certs-only",
  284: "application/pkcs8",
  285: "application/csrattrs",
  286: "application/pkcs10",
  287: "application/pkix-cert",
  290: "application/aif+cbor",
  291: "application/aif+json",
  292: "application/aif+cbor;toid=CRI-local-part",
  293: "application/sd-cwt",
  294: "application/kb+cwt",
  295: "application/measured-component+cbor",
  296: "application/measured-component+json",
  297: "application/aif+cbor;toid=oscore-gname;tperm=oscore-gperm",
  298: "application/aif+json;toid=oscore-gname;tperm=oscore-gperm",
  299: "application/cose-c509-cert+cbor",
  300: "application/cose-c509+cbor",
  301: "application/cose-c509+cbor;usage=chain",
  302: "application/cose-c509-pkcs10+cbor",
  303: "application/cose-c509-crtemplate+cbor",
  304: "application/cose-c509-privkey+cbor",
  305: "application/cose-c509-pem+cbor",
  306: "application/cose-certhash+cbor",
  307: "application/cose-certhash+cbor;usage=c509",
  310: "application/senml+xml",
  311: "application/sensml+xml",
  320: "application/senml-etch+json",
  322: "application/senml-etch+cbor",
  340: "application/yang-data+cbor",
  341: "application/yang-data+cbor; id=name",
  432: "application/td+json",
  433: "application/tm+json",
  434: "application/sdf+json",
  553: "application/dns-message",
  601: "application/uccs+cbor",
  836: "application/voucher+cose",
  10000: "application/vnd.ocf+cbor",
  10001: "application/oscore",
  10002: "application/javascript",
  10003: 'application/eat+cwt; eat_profile="tag:psacertified.org,2023:psa#tfm"',
  10004: 'application/eat+cwt; eat_profile="tag:psacertified.org,2019:psa#legacy"',
  10005: "application/eat+cwt; eat_profile=2.16.840.1.113741.1.16.1",
  10006: "application/vnd.oms.cellular-cose-content+cbor",
  10007: "application/syslog-msg",
  10570: "application/toc+cbor",
  10571: "application/ce+cbor",
  10572: "application/toc+cbor;profile=2.16.840.1.113741.1.16.1",
  10573: "application/ce+cbor;profile=2.16.840.1.113741.1.16.1",
  11542: "application/vnd.oma.lwm2m+tlv",
  11543: "application/vnd.oma.lwm2m+json",
  11544: "application/vnd.oma.lwm2m+cbor",
  20000: "text/css",
  20001: "application/vnd.as207960.vas.config+jer",
  20002: "application/vnd.as207960.vas.config+uper",
  20003: "application/vnd.as207960.vas.tap+jer",
  20004: "application/vnd.as207960.vas.tap+uper",
  30000: "image/svg+xml",
};
