mongo:
  host: localhost
  port: 27017
  username: root
  password: example

oauth:
  client_id: 8da48653-ba29-416e-b882-393b60dce178
  client_secret: siKP6qVeEoBxTOPV4Q4Ijiy6laUhgKXaZfrSYWJKBm3IfiO04fie7KIeFJdIbFUJ

redis:
  host: localhost
  port: 6379

server:
  domain: https://development.lindorm.io
  issuer: https://device.development.lindorm.io
  host: http://device-service
  port: 3000
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://communication-service
    port: 3000
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://oauth-service
    port: 3000
  vault_service:
    issuer: https://vault.development.lindorm.io
    host: http://vault-service
    port: 3000
