version: "3.7"

services:
  oauth_service_mongo:
    image: mongo
    container_name: oauth_service_mongo
    labels:
      - mongo
    ports:
      - "3501:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  oauth_service_redis:
    image: redis
    container_name: oauth_service_redis
    labels:
      - redis
    ports:
      - "3502:6379"
