oauth:
  client_id: 3e0ab7aa-f445-4031-ad27-d87ff23d2ce2
  client_secret: 5NTac6bAnSNAWnMh0pCjABmlv1ca6LUml88gaQrQrBU3aNS6W6LpJp9r3ViclTe8

redis:
  host: localhost
  port: 6379

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://oidc.development.lindorm.io
  host: http://oidc-service
  port: 3000
  workers: true

services:
  identity_service:
    issuer: https://identity.development.lindorm.io
    host: http://identity-service
    port: 3000
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://oauth-service
    port: 3000
