import { StrategyHandler } from "../types";
import {
  DeviceChallengeStrategy,
  EmailCodeStrategy,
  EmailOtpStrategy,
  MfaCookieStrategy,
  PasswordBrowserLinkStrategy,
  PasswordStrategy,
  PhoneCodeStrategy,
  PhoneOtpStrategy,
  RdcPushNotificationStrategy,
  RecoveryCodeStrategy,
  SessionAcceptWithCodeStrategy,
  SessionOtpStrategy,
  SessionQrCodeStrategy,
  TimeBasedOtpStrategy,
} from "./implementations";

export const ENABLED_STRATEGIES: Array<StrategyHandler> = [
  // new BankIdSeStrategy(),
  new DeviceChallengeStrategy(),
  new EmailCodeStrategy(),
  new EmailOtpStrategy(),
  new MfaCookieStrategy(),
  new PasswordBrowserLinkStrategy(),
  new PasswordStrategy(),
  new PhoneCodeStrategy(),
  new PhoneOtpStrategy(),
  new RdcPushNotificationStrategy(),
  // new RdcQrCodeStrategy(),
  new RecoveryCodeStrategy(),
  new SessionAcceptWithCodeStrategy(),
  new SessionOtpStrategy(),
  new SessionQrCodeStrategy(),
  new TimeBasedOtpStrategy(),
  // new WebauthnStrategy(),
];
