export enum AuthenticationStrategy {
  BANK_ID_SE = "bank_id_se",
  DEVICE_CHALLENGE = "device_challenge",
  EMAIL_CODE = "email_code",
  EMAIL_OTP = "email_otp",
  MFA_COOKIE = "mfa_cookie",
  PASSWORD = "password",
  PASSWORD_BROWSER_LINK = "password_browser_link",
  PHONE_CODE = "phone_code",
  PHONE_OTP = "phone_otp",
  RDC_PUSH_NOTIFICATION = "rdc_push_notification",
  RDC_QR_CODE = "rdc_qr_code",
  RECOVERY_CODE = "recovery_code",
  SESSION_DISPLAY_CODE = "session_display_code",
  SESSION_OTP = "session_otp",
  SESSION_QR_CODE = "session_qr_code",
  TIME_BASED_OTP = "time_based_otp",
  WEBAUTHN = "webauthn",
}
