frontend:
  host: http://localhost
  port: 4400

mongo:
  host: localhost
  port: 27017
  username: root
  password: example

redis:
  host: localhost
  port: 6379

oauth:
  client_id: 9993fa84-bedf-4a93-a421-1f63719cd9d3
  client_secret: SXYF5eM47qn2fpqLkaeoy6c1R0AHKPssz0TfCpM3evxJzNasfrgaeFeMByJLmhpq

server:
  domain: https://development.lindorm.io
  issuer: https://identity.development.lindorm.io
  host: http://identity-service
  port: 3000
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://communication-service
    port: 3000
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://oauth-service
    port: 3000
