import {
  ASN1_CONTEXT_CONSTRUCTED_BASE,
  ASN1_TAG_BIT_STRING,
  ASN1_TAG_BOOLEAN,
  ASN1_TAG_GENERALIZED_TIME,
  ASN1_TAG_INTEGER,
  ASN1_TAG_NULL,
  ASN1_TAG_OCTET_STRING,
  ASN1_TAG_OID,
  ASN1_TAG_PRINTABLE_STRING,
  ASN1_TAG_SEQUENCE,
  ASN1_TAG_SET,
  ASN1_TAG_UTC_TIME,
  ASN1_TAG_UTF8_STRING,
} from "./tags";
import { describe, expect, test } from "vitest";

describe("asn1 tags", () => {
  test("match DER constants", () => {
    expect({
      ASN1_CONTEXT_CONSTRUCTED_BASE,
      ASN1_TAG_BIT_STRING,
      ASN1_TAG_BOOLEAN,
      ASN1_TAG_GENERALIZED_TIME,
      ASN1_TAG_INTEGER,
      ASN1_TAG_NULL,
      ASN1_TAG_OCTET_STRING,
      ASN1_TAG_OID,
      ASN1_TAG_PRINTABLE_STRING,
      ASN1_TAG_SEQUENCE,
      ASN1_TAG_SET,
      ASN1_TAG_UTC_TIME,
      ASN1_TAG_UTF8_STRING,
    }).toEqual({
      ASN1_CONTEXT_CONSTRUCTED_BASE: 0xa0,
      ASN1_TAG_BIT_STRING: 0x03,
      ASN1_TAG_BOOLEAN: 0x01,
      ASN1_TAG_GENERALIZED_TIME: 0x18,
      ASN1_TAG_INTEGER: 0x02,
      ASN1_TAG_NULL: 0x05,
      ASN1_TAG_OCTET_STRING: 0x04,
      ASN1_TAG_OID: 0x06,
      ASN1_TAG_PRINTABLE_STRING: 0x13,
      ASN1_TAG_SEQUENCE: 0x30,
      ASN1_TAG_SET: 0x31,
      ASN1_TAG_UTC_TIME: 0x17,
      ASN1_TAG_UTF8_STRING: 0x0c,
    });
  });
});
