export {
  KRYPTOS_AKP_SIG_ML_DSA_44 as TEST_AKP_KEY_ML_DSA_44,
  KRYPTOS_AKP_SIG_ML_DSA_65 as TEST_AKP_KEY_ML_DSA_65,
  KRYPTOS_AKP_SIG_ML_DSA_87 as TEST_AKP_KEY_ML_DSA_87,
} from "@lindorm/kryptos/fixtures";
