version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_hbqYxzId
    ports:
      - "5004:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  postgres:
    image: postgres
    restart: always
    container_name: postgres_hbqYxzId
    ports:
      - "5003:5432"
    environment:
      POSTGRES_DB: default_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example

  rabbitmq:
    image: rabbitmq
    restart: always
    container_name: rabbitmq_hbqYxzId
    ports:
      - "5002:5672"
