import { ClientErrorStatus } from "../enums";

export const CLIENT_ERROR_TITLE: Record<ClientErrorStatus, string> = {
  [ClientErrorStatus.BAD_REQUEST]: "Bad Request",
  [ClientErrorStatus.UNAUTHORIZED]: "Unauthorized",
  [ClientErrorStatus.PAYMENT_REQUIRED]: "Payment Required",
  [ClientErrorStatus.FORBIDDEN]: "Forbidden",
  [ClientErrorStatus.NOT_FOUND]: "Not Found",
  [ClientErrorStatus.METHOD_NOT_ALLOWED]: "Method Not Allowed",
  [ClientErrorStatus.NOT_ACCEPTABLE]: "Not Acceptable",
  [ClientErrorStatus.PROXY_AUTHENTICATION_REQUIRED]: "Proxy Authentication Required",
  [ClientErrorStatus.REQUEST_TIMEOUT]: "Request Timeout",
  [ClientErrorStatus.CONFLICT]: "Conflict",
  [ClientErrorStatus.GONE]: "Gone",
  [ClientErrorStatus.LENGTH_REQUIRED]: "Length Required",
  [ClientErrorStatus.PRECONDITION_FAILED]: "Precondition Failed",
  [ClientErrorStatus.PAYLOAD_TOO_LARGE]: "Payload Too Large",
  [ClientErrorStatus.REQUEST_URI_TOO_LONG]: "Request-URI Too Long",
  [ClientErrorStatus.UNSUPPORTED_MEDIA_TYPE]: "Unsupported Media Type",
  [ClientErrorStatus.REQUESTED_RANGE_NOT_SATISFIABLE]: "Requested Range Not Satisfiable",
  [ClientErrorStatus.EXPECTATION_FAILED]: "Expectation Failed",
  [ClientErrorStatus.IM_A_TEAPOT]: "I'm a teapot",
  [ClientErrorStatus.MISDIRECTED_REQUEST]: "Misdirected Request",
  [ClientErrorStatus.UNPROCESSABLE_ENTITY]: "Unprocessable Entity",
  [ClientErrorStatus.LOCKED]: "Locked",
  [ClientErrorStatus.FAILED_DEPENDENCY]: "Failed Dependency",
  [ClientErrorStatus.UPGRADE_REQUIRED]: "Upgrade Required",
  [ClientErrorStatus.PRECONDITION_REQUIRED]: "Precondition Required",
  [ClientErrorStatus.TOO_MANY_REQUESTS]: "Too Many Requests",
  [ClientErrorStatus.REQUEST_HEADER_FIELDS_TOO_LARGE]: "Request Header Fields Too Large",
  [ClientErrorStatus.CONNECTION_CLOSED_WITHOUT_RESPONSE]: "Connection Closed Without Response",
  [ClientErrorStatus.UNAVAILABLE_FOR_LEGAL_REASONS]: "Unavailable For Legal Reasons",
  [ClientErrorStatus.CLIENT_CLOSED_REQUEST]: "Client Closed Request",
} as const;
