frontend:
  host: http://localhost
  port: 4600

logger:
  level: debug
  colours: true
  readable: true
  timestamp: true

oauth:
  client_id: 3e0ab7aa-f445-4031-ad27-d87ff23d2ce2
  client_secret: rjasuBK8yLFR68_n6J_ySa0WA3gwAQN-NHEvVxAMzQDeuqP_lxHY4LN-JTmeXp7R

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://federation.development.lindorm.io
  host: http://localhost
  port: 3006
  workers: true

services:
  identity_service:
    issuer: https://identity.development.lindorm.io
    host: http://localhost
    port: 3004
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3005
