import { ReverseMap } from "@lindorm-io/common-types";

export const ClientScopes = {
  COMMUNICATION_EVENT_EMIT: "lindorm.io/communication-service/client/event:emit",
  COMMUNICATION_MESSAGE_SEND: "lindorm.io/communication-service/client/message:send",
  DEVICE_IDENTITY_READ: "lindorm.io/device-service/client/identity:read",
  DEVICE_RDC_READ: "lindorm.io/device-service/client/rdc:read",
  DEVICE_RDC_WRITE: "lindorm.io/device-service/client/rdc:write",
  IDENTITY_IDENTIFIER_READ: "lindorm.io/identity-service/client/identifier:read",
  IDENTITY_IDENTIFIER_WRITE: "lindorm.io/identity-service/client/identifier:write",
  IDENTITY_IDENTITY_READ: "lindorm.io/identity-service/client/identity:read",
  IDENTITY_IDENTITY_WRITE: "lindorm.io/identity-service/client/identity:write",
  OAUTH_AUTHENTICATION_READ: "lindorm.io/oauth-service/client/authentication:read",
  OAUTH_AUTHENTICATION_WRITE: "lindorm.io/oauth-service/client/authentication:write",
  OAUTH_CLIENT_READ: "lindorm.io/oauth-service/client/client:read",
  OAUTH_CLIENT_WRITE: "lindorm.io/oauth-service/client/client:write",
  OAUTH_CONSENT_READ: "lindorm.io/oauth-service/client/consent:read",
  OAUTH_CONSENT_WRITE: "lindorm.io/oauth-service/client/consent:write",
  OAUTH_ELEVATION_READ: "lindorm.io/oauth-service/client/elevation:read",
  OAUTH_ELEVATION_WRITE: "lindorm.io/oauth-service/client/elevation:write",
  OAUTH_IDENTITY_READ: "lindorm.io/oauth-service/client/identity:read",
  OAUTH_IDENTITY_WRITE: "lindorm.io/oauth-service/client/identity:write",
  OAUTH_LOGOUT_READ: "lindorm.io/oauth-service/client/logout:read",
  OAUTH_LOGOUT_WRITE: "lindorm.io/oauth-service/client/logout:write",
  OAUTH_TENANT_READ: "lindorm.io/oauth-service/client/tenant:read",
  OAUTH_TENANT_WRITE: "lindorm.io/oauth-service/client/tenant:write",
  OIDC_SESSION_READ: "lindorm.io/oidc-service/client/session:read",
  OIDC_SESSION_WRITE: "lindorm.io/oidc-service/client/session:write",
  VAULT_ENCRYPTED_RECORD_READ: "lindorm.io/vault-service/client/encrypted-record:read",
  VAULT_ENCRYPTED_RECORD_WRITE: "lindorm.io/vault-service/client/encrypted-record:write",
  VAULT_JWKS_PRIVATE_READ: "lindorm.io/vault-service/client/jwks-private:read",
  VAULT_PROTECTED_RECORD_READ: "lindorm.io/vault-service/client/protected-record:read",
  VAULT_PROTECTED_RECORD_WRITE: "lindorm.io/vault-service/client/protected-record:write",
} as const;

export type ClientScope = ReverseMap<typeof ClientScopes>;
