export enum ClientScope {
  COMMUNICATION_EVENT_EMIT = "lindorm.io:communication:event:emit",
  COMMUNICATION_MESSAGE_SEND = "lindorm.io:communication:message:send",
  DEVICE_IDENTITY_READ = "lindorm.io:device:identity:read",
  DEVICE_RDC_READ = "lindorm.io:device:rdc:read",
  DEVICE_RDC_WRITE = "lindorm.io:device:rdc:write",
  IDENTITY_IDENTIFIER_READ = "lindorm.io:identity:identifier:read",
  IDENTITY_IDENTIFIER_WRITE = "lindorm.io:identity:identifier:write",
  IDENTITY_IDENTITY_READ = "lindorm.io:identity:identity:read",
  IDENTITY_IDENTITY_WRITE = "lindorm.io:identity:identity:write",
  OAUTH_AUTHENTICATION_READ = "lindorm.io:oauth:authentication:read",
  OAUTH_AUTHENTICATION_WRITE = "lindorm.io:oauth:authentication:write",
  OAUTH_CLIENT_DELETE = "lindorm.io:oauth:client:delete",
  OAUTH_CLIENT_READ = "lindorm.io:oauth:client:read",
  OAUTH_CLIENT_WRITE = "lindorm.io:oauth:client:write",
  OAUTH_CONSENT_READ = "lindorm.io:oauth:consent:read",
  OAUTH_CONSENT_WRITE = "lindorm.io:oauth:consent:write",
  OAUTH_IDENTITY_READ = "lindorm.io:oauth:identity:read",
  OAUTH_LOGOUT_READ = "lindorm.io:oauth:logout:read",
  OAUTH_LOGOUT_WRITE = "lindorm.io:oauth:logout:write",
}
