mongo:
  host: localhost
  port: 27017
  username: root
  password: example

oauth:
  client_id: c233687a-c610-412c-985b-5f6e95fbf47d
  client_secret: aOpwpLy8XQhxExub2h68K0Puddy5CM9FO1v1XSZVIhvoSRvGlv0Fih6ofUCrwNmx

redis:
  host: localhost
  port: 6379

server:
  domain: https://development.lindorm.io
  issuer: https://vault.development.lindorm.io
  host: http://vault-service
  port: 3000
  workers: true

services:
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://oauth-service
    port: 3000
