frontend:
  host: http://localhost
  port: 4500

mongo:
  host: localhost
  port: 27017
  username: root
  password: example

oauth:
  client_id: 6e4d37bf-6121-4851-9229-52ea6530a297

redis:
  host: localhost
  port: 6379

server:
  domain: https://development.lindorm.io
  issuer: https://oauth.development.lindorm.io
  host: http://oauth-service
  keys:
    - secret
  port: 3000
  workers: true

services:
  authentication_service:
    issuer: https://authentication.development.lindorm.io
    host: http://authentication-service
    port: 3000
  identity_service:
    issuer: https://identity.development.lindorm.io
    host: http://identity-service
    port: 3000
