import { HttpStatus, Router } from "@lindorm-io/koa";
import { LindormScopes, OauthGrantTypes, OauthResponseTypes } from "@lindorm-io/common-types";
import { ServerKoaContext } from "../../types";
import { configuration } from "../../server/configuration";

const router = new Router<any, any>();
export default router;

router.get("/", async (ctx: ServerKoaContext): Promise<void> => {
  ctx.body = {
    authorizationEndpoint: new URL("/oauth2/authorize", configuration.server.host).toString(),
    backchannelLogoutSessionSupported: true,
    backchannelLogoutSupported: true,
    claimsParameterSupported: false,
    endSessionEndpoint: new URL("/oauth2/sessions/logout", configuration.server.host).toString(),
    grantTypesSupported: [
      OauthGrantTypes.AUTHORIZATION_CODE,
      OauthGrantTypes.CLIENT_CREDENTIALS,
      OauthGrantTypes.REFRESH_TOKEN,
    ],
    idTokenEncryptionAlgValuesSupported: [],
    idTokenEncryptionEncValuesSupported: [],
    idTokenSigningAlgValuesSupported: ["ES512", "RS512"],
    issuer: configuration.server.issuer,
    jwksUri: new URL("/.well-known/jwks.json", configuration.server.host).toString(),
    logoutEndpoint: new URL("/oauth2/sessions/logout", configuration.server.host).toString(),
    requestParameterSupported: false,
    requestUriParameterSupported: true,
    responseTypesSupported: [
      OauthResponseTypes.CODE,
      OauthResponseTypes.ID_TOKEN,
      OauthResponseTypes.TOKEN,

      [OauthResponseTypes.CODE, OauthResponseTypes.ID_TOKEN].join(" "),
      [OauthResponseTypes.CODE, OauthResponseTypes.TOKEN].join(" "),
      [OauthResponseTypes.ID_TOKEN, OauthResponseTypes.TOKEN].join(" "),

      [OauthResponseTypes.CODE, OauthResponseTypes.ID_TOKEN, OauthResponseTypes.TOKEN].join(" "),
    ],
    revokeEndpoint: new URL("/oauth2/sessions/revoke", configuration.server.host).toString(),
    claimsSupported: [
      "aal",
      "acr",
      "address",
      "amr",
      "aud",
      "auth_time",
      "azp",
      "birth_date",
      "connected_providers",
      "display_name",
      "email",
      "email_verified",
      "exp",
      "ext",
      "family_name",
      "gender",
      "given_name",
      "gravatar_uri",
      "iat",
      "iss",
      "jti",
      "loa",
      "locale",
      "middle_name",
      "name",
      "national_identity_number",
      "national_identity_number_verified",
      "nbf",
      "nickname",
      "nonce",
      "phone_number",
      "phone_number_verified",
      "picture",
      "preferred_accessibility",
      "preferred_username",
      "profile",
      "pronouns",
      "scp",
      "sid",
      "sih",
      "social_security_number",
      "social_security_number_verified",
      "sub",
      "suh",
      "taken_name",
      "tid",
      "token_type",
      "usr",
      "website",
      "zone_info",
    ],
    scopesSupported: [
      LindormScopes.OPENID,
      LindormScopes.ADDRESS,
      LindormScopes.EMAIL,
      LindormScopes.PHONE,
      LindormScopes.PROFILE,

      LindormScopes.ACCESSIBILITY,
      LindormScopes.CONNECTED_PROVIDERS,
      LindormScopes.NATIONAL_IDENTITY_NUMBER,
      LindormScopes.PUBLIC,
      LindormScopes.SOCIAL_SECURITY_NUMBER,
      LindormScopes.USERNAME,

      LindormScopes.OFFLINE_ACCESS,
    ],
    subjectTypesSupported: ["identity", "client"],
    tokenEndpoint: new URL("/oauth2/token", configuration.server.host).toString(),
    tokenEndpointAuthMethodsSupported: ["client_secret_basic", "client_secret_post"],
    tokenEndpointAuthSigningAlgValuesSupported: ["ES512", "RS512"],
    tokeninfoEndpoint: new URL("/tokeninfo", configuration.server.host).toString(),
    userinfoEndpoint: new URL("/userinfo", configuration.server.host).toString(),
  };
  ctx.status = HttpStatus.Success.OK;
});
