mongo:
  host: localhost
  port: 3401
  db_name: identity
  username: root
  password: example

redis:
  host: localhost
  port: 3402

oauth:
  client_id: 9993fa84-bedf-4a93-a421-1f63719cd9d3
  client_secret: bAJL5tCZr5lWBmJieQKqyFN9mBf8qN1G00YlIlTMtURg3gxJyFUSHvNvCTje3rdXNTifCX4xZHXeX8hvcWjgpmaZv9dS79OX2wK25XCl3NCI7DTwHIrBzL1zzh6A2uOb

server:
  domain: https://development.lindorm.io
  environment: development
  host: http://localhost
  issuer: https://identity.development.lindorm.io
  port: 3400
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://localhost
    port: 3200
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3500
