mongo:
  host: localhost
  port: 3401
  db_name: identity
  username: root
  password: example

redis:
  host: localhost
  port: 3402

oauth:
  host: http://localhost:3500
  client_id: secret
  client_secret: secret

server:
  environment: development
  host: http://localhost
  port: 3400

services:
  communication_service: http://localhost:3200
