oauth:
  host: https://oauth.api.lindorm.io

redis:
  username: username
  password: password

server:
  environment: production
  host: https://identity.api.lindorm.io

services:
  communication_service: https://communication.api.lindorm.io
