frontend:
  host: https://frontend.url/

mongo:
  host: localhost
  port: 3401
  db_name: identity
  username: root
  password: example

oauth:
  client_id: id
  client_secret: secret

redis:
  host: localhost
  port: 3402

server:
  domain: https://test.lindorm.io
  environment: test
  host: https://identity.test.lindorm.io
  issuer: https://identity.test.lindorm.io
  port: 3400
  workers: false

services:
  communication_service:
    host: https://communication.test.lindorm.io
  oauth_service:
    host: https://oauth.test.lindorm.io
