mongo:
  host: localhost
  port: 3401
  db_name: identity
  username: root
  password: example

oauth:
  host: https://oauth.test.api.lindorm.io
  client_id: secret
  client_secret: secret

redis:
  host: localhost
  port: 3402

server:
  environment: test
  host: https://identity.test.api.lindorm.io
  port: 3400

services:
  communication_service: https://communication.test.api.lindorm.io
