import { AuthenticationMethod, AuthenticationStrategy } from "@lindorm-io/common-types";
import { createTestAuthenticationSession } from "../fixtures/entity";
import { generateClientConfig } from "./generate-client-config";

describe("calculateMethodsAndStrategies", () => {
  test("should resolve client config", () => {
    expect(
      generateClientConfig(
        createTestAuthenticationSession({
          allowedStrategies: Object.values(AuthenticationStrategy),
          recommendedMethods: [],
          requiredLevel: 1,
          requiredMethods: [],
        }),
      ),
    ).toStrictEqual([
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "mfa_cookie",
        rank: 1,
        recommended: false,
        required: false,
        strategies: [{ strategy: "mfa_cookie", weight: 999 }],
        weight: 999,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "device_link",
        rank: 2,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "rdc_push_notification", weight: 90 },
          { strategy: "rdc_qr_code", weight: 90 },
          { strategy: "device_challenge", weight: 90 },
        ],
        weight: 90,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "totp",
        rank: 3,
        recommended: false,
        required: false,
        strategies: [{ strategy: "time_based_otp", weight: 90 }],
        weight: 90,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "session_link",
        rank: 4,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "session_otp", weight: 80 },
          { strategy: "session_qr_code", weight: 80 },
          { strategy: "session_display_code", weight: 80 },
        ],
        weight: 80,
      },
      {
        hint: "test@lindorm.io",
        hintType: "email",
        identifierType: "email",
        method: "email",
        rank: 5,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "email_otp", weight: 30 },
          { strategy: "email_code", weight: 10 },
        ],
        weight: 30,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "username",
        method: "password",
        rank: 6,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "password_browser_link", weight: 20 },
          { strategy: "password", weight: 10 },
        ],
        weight: 20,
      },
      {
        hint: "0701234567",
        hintType: "phone",
        identifierType: "phone",
        method: "phone",
        rank: 7,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "phone_otp", weight: 20 },
          { strategy: "phone_code", weight: 10 },
        ],
        weight: 20,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "recovery",
        rank: 8,
        recommended: false,
        required: false,
        strategies: [{ strategy: "recovery_code", weight: 0 }],
        weight: 0,
      },
    ]);
  });

  test("should calculate based on recommended methods", () => {
    expect(
      generateClientConfig(
        createTestAuthenticationSession({
          allowedStrategies: Object.values(AuthenticationStrategy),
          recommendedMethods: [AuthenticationMethod.PASSWORD, AuthenticationMethod.EMAIL],
          requiredLevel: 1,
          requiredMethods: [],
        }),
      ),
    ).toStrictEqual([
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "mfa_cookie",
        rank: 1,
        recommended: false,
        required: false,
        strategies: [{ strategy: "mfa_cookie", weight: 999 }],
        weight: 999,
      },
      {
        hint: "test@lindorm.io",
        hintType: "email",
        identifierType: "email",
        method: "email",
        rank: 2,
        recommended: true,
        required: false,
        strategies: [
          { strategy: "email_otp", weight: 750 },
          { strategy: "email_code", weight: 250 },
        ],
        weight: 750,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "username",
        method: "password",
        rank: 3,
        recommended: true,
        required: false,
        strategies: [
          { strategy: "password_browser_link", weight: 500 },
          { strategy: "password", weight: 250 },
        ],
        weight: 500,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "device_link",
        rank: 4,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "rdc_push_notification", weight: 90 },
          { strategy: "rdc_qr_code", weight: 90 },
          { strategy: "device_challenge", weight: 90 },
        ],
        weight: 90,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "totp",
        rank: 5,
        recommended: false,
        required: false,
        strategies: [{ strategy: "time_based_otp", weight: 90 }],
        weight: 90,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "session_link",
        rank: 6,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "session_otp", weight: 80 },
          { strategy: "session_qr_code", weight: 80 },
          { strategy: "session_display_code", weight: 80 },
        ],
        weight: 80,
      },
      {
        hint: "0701234567",
        hintType: "phone",
        identifierType: "phone",
        method: "phone",
        rank: 7,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "phone_otp", weight: 20 },
          { strategy: "phone_code", weight: 10 },
        ],
        weight: 20,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "recovery",
        rank: 8,
        recommended: false,
        required: false,
        strategies: [{ strategy: "recovery_code", weight: 0 }],
        weight: 0,
      },
    ]);
  });

  test("should calculate based on required methods", () => {
    expect(
      generateClientConfig(
        createTestAuthenticationSession({
          allowedStrategies: Object.values(AuthenticationStrategy),
          recommendedMethods: [],
          requiredLevel: 1,
          requiredMethods: [AuthenticationMethod.PASSWORD, AuthenticationMethod.EMAIL],
        }),
      ),
    ).toStrictEqual([
      {
        hint: "test@lindorm.io",
        hintType: "email",
        identifierType: "email",
        method: "email",
        rank: 1,
        recommended: false,
        required: true,
        strategies: [
          { strategy: "email_otp", weight: 3000 },
          { strategy: "email_code", weight: 1000 },
        ],
        weight: 3000,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "username",
        method: "password",
        rank: 2,
        recommended: false,
        required: true,
        strategies: [
          { strategy: "password_browser_link", weight: 2000 },
          { strategy: "password", weight: 1000 },
        ],
        weight: 2000,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "mfa_cookie",
        rank: 3,
        recommended: false,
        required: false,
        strategies: [{ strategy: "mfa_cookie", weight: 999 }],
        weight: 999,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "device_link",
        rank: 4,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "rdc_push_notification", weight: 90 },
          { strategy: "rdc_qr_code", weight: 90 },
          { strategy: "device_challenge", weight: 90 },
        ],
        weight: 90,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "totp",
        rank: 5,
        recommended: false,
        required: false,
        strategies: [{ strategy: "time_based_otp", weight: 90 }],
        weight: 90,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "session_link",
        rank: 6,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "session_otp", weight: 80 },
          { strategy: "session_qr_code", weight: 80 },
          { strategy: "session_display_code", weight: 80 },
        ],
        weight: 80,
      },
      {
        hint: "0701234567",
        hintType: "phone",
        identifierType: "phone",
        method: "phone",
        rank: 7,
        recommended: false,
        required: false,
        strategies: [
          { strategy: "phone_otp", weight: 20 },
          { strategy: "phone_code", weight: 10 },
        ],
        weight: 20,
      },
      {
        hint: null,
        hintType: "none",
        identifierType: "none",
        method: "recovery",
        rank: 8,
        recommended: false,
        required: false,
        strategies: [{ strategy: "recovery_code", weight: 0 }],
        weight: 0,
      },
    ]);
  });
});
