version: "3.7"

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres_10
    labels:
      - postgres
    ports:
      - "5010:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: default
