import { B64 } from "@lindorm/b64";
import { decode } from "cbor2";
import { KryptosError } from "../../../errors/index.js";
import type { KryptosOperation, LindormJwk } from "../../../types/index.js";
import { CBOR_LABEL, CBOR_VERSION } from "../../constants/cbor-table.js";
import type { CborMaterialKey } from "./cbor-material-keys.js";
import {
  REV_ALG,
  REV_CRV,
  REV_ENC,
  REV_KTY,
  REV_LABEL,
  REV_OPS,
  REV_USE,
} from "./cbor-reverse.js";

const fail = (details: string, data?: Record<string, unknown>): never => {
  throw new KryptosError(details, {
    code: "invalid_cbor_env",
    title: "Invalid CBOR Env String",
    details,
    data,
  });
};

const asText = (value: unknown, field: string): string =>
  typeof value === "string"
    ? value
    : fail(`CBOR field "${field}" must be a text string.`, { field });

const asInt = (value: unknown, field: string): number =>
  typeof value === "number" && Number.isInteger(value)
    ? value
    : fail(`CBOR field "${field}" must be an integer.`, { field });

const asBool = (value: unknown, field: string): boolean =>
  typeof value === "boolean"
    ? value
    : fail(`CBOR field "${field}" must be a boolean.`, { field });

const asBytes = (value: unknown, field: string): Uint8Array =>
  value instanceof Uint8Array
    ? value
    : fail(`CBOR field "${field}" must be a byte string.`, { field });

const enumName = <V extends string>(
  rev: Map<number, V>,
  value: unknown,
  field: string,
): V => {
  if (typeof value !== "number" || !rev.has(value)) {
    return fail(`Unknown CBOR ${field} value "${String(value)}".`, {
      field,
      value,
    });
  }
  return rev.get(value)!;
};

const decodeKeyOps = (value: unknown): Array<KryptosOperation> => {
  if (!Array.isArray(value)) return fail(`CBOR field "key_ops" must be an array.`);
  return value.map((op) => enumName(REV_OPS, op, "key_ops"));
};

const decodeX5c = (value: unknown): Array<string> => {
  if (!Array.isArray(value)) return fail(`CBOR field "x5c" must be an array.`);
  return value.map((der) => B64.encode(asBytes(der, "x5c"), "base64"));
};

// Strictly decode the kryptos CBOR wire map back into a private LindormJwk, ready
// for the ordinary JWK import path. Unknown labels, unknown enum values, and a
// future format version all throw — this format is versioned and closed.
export const decodeCborEnv = (bytes: Uint8Array): LindormJwk => {
  const map = decode<unknown>(bytes, { preferMap: true });

  if (!(map instanceof Map)) {
    return fail("A CBOR env string must decode to a map.");
  }

  const version = map.get(CBOR_LABEL.version);
  if (typeof version !== "number") {
    return fail("A CBOR env string must carry an integer version at label 0.");
  }
  if (version > CBOR_VERSION) {
    return fail(
      `This CBOR env string was generated by a newer kryptos (format version ${version} > ${CBOR_VERSION}). Upgrade @lindorm/kryptos to import it.`,
      { version, supported: CBOR_VERSION },
    );
  }

  const jwk: Partial<LindormJwk> = {};

  for (const [label, value] of map) {
    switch (label) {
      case CBOR_LABEL.version:
        break;

      case CBOR_LABEL.kty:
        jwk.kty = enumName(REV_KTY, value, "kty");
        break;

      case CBOR_LABEL.alg:
        jwk.alg = enumName(REV_ALG, value, "alg");
        break;

      case CBOR_LABEL.use:
        jwk.use = enumName(REV_USE, value, "use");
        break;

      case CBOR_LABEL.crv:
        jwk.crv = enumName(REV_CRV, value, "crv");
        break;

      case CBOR_LABEL.enc:
        jwk.enc = enumName(REV_ENC, value, "enc");
        break;

      case CBOR_LABEL.key_ops:
        jwk.key_ops = decodeKeyOps(value);
        break;

      case CBOR_LABEL.kid:
        jwk.kid = asText(value, "kid");
        break;

      case CBOR_LABEL.iss:
        jwk.iss = asText(value, "iss");
        break;

      case CBOR_LABEL.jku:
        jwk.jku = asText(value, "jku");
        break;

      case CBOR_LABEL.purpose:
        jwk.purpose = asText(value, "purpose");
        break;

      case CBOR_LABEL.owner_id:
        jwk.owner_id = asText(value, "owner_id");
        break;

      case CBOR_LABEL.exp:
        jwk.exp = asInt(value, "exp");
        break;

      case CBOR_LABEL.iat:
        jwk.iat = asInt(value, "iat");
        break;

      case CBOR_LABEL.nbf:
        jwk.nbf = asInt(value, "nbf");
        break;

      case CBOR_LABEL.hidden:
        jwk.hidden = asBool(value, "hidden");
        break;

      case CBOR_LABEL.x5c:
        jwk.x5c = decodeX5c(value);
        break;

      case CBOR_LABEL.x:
      case CBOR_LABEL.y:
      case CBOR_LABEL.d:
      case CBOR_LABEL.n:
      case CBOR_LABEL.e:
      case CBOR_LABEL.p:
      case CBOR_LABEL.q:
      case CBOR_LABEL.dp:
      case CBOR_LABEL.dq:
      case CBOR_LABEL.qi:
      case CBOR_LABEL.k:
      case CBOR_LABEL.pub:
      case CBOR_LABEL.priv: {
        const member = REV_LABEL.get(label) as CborMaterialKey;
        jwk[member] = B64.encode(asBytes(value, member), "b64u");
        break;
      }

      default:
        return fail(`Unknown CBOR label "${String(label)}".`, { label });
    }
  }

  return jwk as LindormJwk;
};
