defaults:
  authentication_session_expiry: 30 minutes
  browser_link_cookie_expiry: 100 years
  mfa_cookie_expiry: 75 minutes

frontend:
  host: http://localhost
  routes:
    auth: /auth
    code_callback: /code/callback
    consent: /consent
    error: /error
    login: /login
    logout: /logout

logger:
  level: info
  colours: false
  readable: false
  timestamp: true

mongo:
  host: localhost
  port: 27017
  db_name: authentication_db
  username: root
  password: example

oauth:
  client_id: id
  client_secret: secret

redis:
  host: localhost
  port: 6379
  namespace: authentication_service

server:
  domain: https://lindorm.io
  environment: development
  issuer: https://authentication.lindorm.io
  host: http://localhost
  keys: []
  port: 3000
  workers: false

services:
  communication_service:
    client_name: communicationClient
    issuer: https://communication.lindorm.io
    host: http://localhost
  device_service:
    client_name: deviceClient
    issuer: https://device.lindorm.io
    host: http://localhost
  identity_service:
    client_name: identityClient
    issuer: https://identity.lindorm.io
    host: http://localhost
  oauth_service:
    client_name: oauthClient
    issuer: https://oauth.lindorm.io
    host: http://localhost
  oidc_service:
    client_name: oidcClient
    issuer: https://oidc.lindorm.io
    host: http://localhost
  vault_service:
    client_name: vaultClient
    issuer: https://vault.lindorm.io
    host: http://localhost
