frontend:
  host: http://localhost
  port: 4100

mongo:
  host: localhost
  port: 3101
  username: root
  password: example

oauth:
  client_id: f39e83c0-10d8-49a1-8ecb-bb89f1d57b7f
  client_secret: kHuCFwhRR3joU3sjMPiKC0P5XwB62AAoYHJ6H9T6jJcYcpm3Vnj9AyYDIJGttD1E

redis:
  host: localhost
  port: 3102

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://authentication.development.lindorm.io
  host: http://localhost
  keys:
    - secret
  port: 3100
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://localhost
    port: 3200
  device_service:
    issuer: https://device.development.lindorm.io
    host: http://localhost
    port: 3300
  identity_service:
    issuer: https://identity.development.lindorm.io
    host: http://localhost
    port: 3400
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://localhost
    port: 3500
  oidc_service:
    issuer: https://oidc.development.lindorm.io
    host: http://localhost
    port: 3600
  vault_service:
    issuer: https://vault.development.lindorm.io
    host: http://localhost
    port: 3700
