redis:
  username: username
  password: password

server:
  domain: https://lindorm.io
  issuer: https://authentication.lindorm.io
  host: https://authentication.lindorm.io
  workers: true

services:
  communication_service:
    host: https://communication.lindorm.io
  identity_service:
    host: https://identity.lindorm.io
  oauth_service:
    host: https://oauth.lindorm.io
  oidc_service:
    host: https://oidc.lindorm.io
  vault_service:
    host: https://vault.lindorm.io
