redis:
  username: username
  password: password

server:
  domain: https://staging.lindorm.io
  environment: staging
  issuer: https://authentication.staging.lindorm.io
  host: https://authentication.staging.lindorm.io
  workers: true

services:
  communication_service:
    host: https://communication.staging.lindorm.io
  device_service:
    host: https://device.staging.lindorm.io
  identity_service:
    host: https://identity.staging.lindorm.io
  oauth_service:
    host: https://oauth.staging.lindorm.io
  oidc_service:
    host: https://oidc.staging.lindorm.io
  vault_service:
    host: https://vault.staging.lindorm.io
