frontend:
  host: https://frontend.url/

mongo:
  host: localhost
  port: 3101
  username: root
  password: example

oauth:
  client_id: id
  client_secret: secret

oidc_providers:
  - key: apple
    loa_value: 3
  - key: google
    loa_value: 2
  - key: microsoft
    loa_value: 2

redis:
  host: localhost
  port: 3102

server:
  domain: https://test.lindorm.io
  issuer: https://authentication.test.lindorm.io
  host: https://authentication.test.lindorm.io
  keys:
    - secret
  port: 3100
  workers: false

services:
  communication_service:
    host: https://communication.test.lindorm.io
  identity_service:
    host: https://identity.test.lindorm.io
  oauth_service:
    host: https://oauth.test.lindorm.io
  oidc_service:
    host: https://oidc.test.lindorm.io
  vault_service:
    host: https://vault.test.lindorm.io
