version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo_94iSCVcH
    ports:
      - "5008:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
