version: "3.7"

services:
  authentication_service_mongo:
    image: mongo
    container_name: authentication_service_mongo
    labels:
      - mongo
    ports:
      - "3101:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  authentication_service_redis:
    image: redis
    container_name: authentication_service_redis
    labels:
      - redis
    ports:
      - "3102:6379"
