frontend:
  host: http://localhost
  port: 4100

mongo:
  host: mongo
  port: 27017
  username: root
  password: example

oauth:
  client_id: f39e83c0-10d8-49a1-8ecb-bb89f1d57b7f
  client_secret: kHuCFwhRR3joU3sjMPiKC0P5XwB62AAoYHJ6H9T6jJcYcpm3Vnj9AyYDIJGttD1E

redis:
  host: redis
  port: 6379

server:
  domain: https://development.lindorm.io
  environment: development
  issuer: https://authentication.development.lindorm.io
  host: http://authentication-service
  keys:
    - secret
  port: 3000
  workers: true

services:
  communication_service:
    issuer: https://communication.development.lindorm.io
    host: http://communication-service
    port: 3000
  device_service:
    issuer: https://device.development.lindorm.io
    host: http://device-service
    port: 3000
  identity_service:
    issuer: https://identity.development.lindorm.io
    host: http://identity-service
    port: 3000
  oauth_service:
    issuer: https://oauth.development.lindorm.io
    host: http://oauth-service
    port: 3000
  oidc_service:
    issuer: https://oidc.development.lindorm.io
    host: http://oidc-service
    port: 3000
  vault_service:
    issuer: https://vault.development.lindorm.io
    host: http://vault-service
    port: 3000
