import { AuthenticationMethod } from "../common";
import { AuthenticationStrategy } from "../enum";
import { InputKey, Hint, InitialiseKey, InputMode } from "../types";
import { LevelOfAssurance } from "@lindorm-io/jwt";

export type AuthenticationStrategyConfig = {
  method: AuthenticationMethod;
  strategy: AuthenticationStrategy;
  amrValuesMax: number;
  amrValuesMin: number;
  confirmKey: InputKey;
  confirmLength: number | null;
  confirmMode: InputMode;
  hint: Hint;
  initialiseKey: InitialiseKey;
  mfaCookie: boolean;
  pollingRequired: boolean;
  tokenReturn: boolean;
  value: LevelOfAssurance;
  valueMax: LevelOfAssurance;
  weight: number;
};

export const AUTHENTICATION_STRATEGY_CONFIG: Array<AuthenticationStrategyConfig> = [
  {
    method: AuthenticationMethod.BANK_ID_SE,
    strategy: AuthenticationStrategy.BANK_ID_SE,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "none",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    value: 4,
    valueMax: 4,
    weight: 90,
  },
  {
    method: AuthenticationMethod.DEVICE_LINK,
    strategy: AuthenticationStrategy.DEVICE_CHALLENGE,
    amrValuesMax: 0,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "challenge_confirmation_token",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: true,
    value: 3,
    valueMax: 3,
    weight: 90,
  },
  {
    method: AuthenticationMethod.EMAIL,
    strategy: AuthenticationStrategy.EMAIL_LINK,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "email",
    confirmKey: "code",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: false,
    value: 2,
    valueMax: 2,
    weight: 10,
  },
  {
    method: AuthenticationMethod.EMAIL,
    strategy: AuthenticationStrategy.EMAIL_OTP,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "email",
    confirmKey: "otp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 2,
    weight: 30,
  },
  {
    method: AuthenticationMethod.MFA_COOKIE,
    strategy: AuthenticationStrategy.MFA_COOKIE,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "none",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 3,
    weight: 999,
  },
  {
    method: AuthenticationMethod.PASSWORD,
    strategy: AuthenticationStrategy.PASSWORD,
    amrValuesMax: 0,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "username",
    confirmKey: "password",
    confirmLength: null,
    confirmMode: "text",
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 3,
    weight: 10,
  },
  {
    method: AuthenticationMethod.PASSWORD,
    strategy: AuthenticationStrategy.PASSWORD_BROWSER_LINK,
    amrValuesMax: 0,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "username",
    confirmKey: "password",
    confirmLength: null,
    confirmMode: "text",
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 3,
    valueMax: 3,
    weight: 20,
  },
  {
    method: AuthenticationMethod.PHONE,
    strategy: AuthenticationStrategy.PHONE_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "phone",
    initialiseKey: "phone_number",
    confirmKey: "otp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 10,
  },
  {
    method: AuthenticationMethod.DEVICE_LINK,
    strategy: AuthenticationStrategy.RDC_PUSH_NOTIFICATION,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "challenge_confirmation_token",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 3,
    weight: 90,
  },
  {
    method: AuthenticationMethod.DEVICE_LINK,
    strategy: AuthenticationStrategy.RDC_QR_CODE,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "challenge_confirmation_token",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 3,
    weight: 90,
  },
  {
    method: AuthenticationMethod.SESSION_LINK,
    strategy: AuthenticationStrategy.SESSION_ACCEPT_WITH_CODE,
    amrValuesMax: 1,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "code",
    confirmLength: 8,
    confirmMode: "text",
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 2,
    weight: 80,
  },
  {
    method: AuthenticationMethod.SESSION_LINK,
    strategy: AuthenticationStrategy.SESSION_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "otp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 80,
  },
  {
    method: AuthenticationMethod.TIME_BASED_OTP,
    strategy: AuthenticationStrategy.TIME_BASED_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "totp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 90,
  },
  {
    method: AuthenticationMethod.WEBAUTHN,
    strategy: AuthenticationStrategy.WEBAUTHN,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "none",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 90,
  },
];
