import {
  AuthenticationMethod,
  AuthenticationMethods,
  AuthenticationStrategies,
  AuthenticationStrategy,
  AuthMethodConfirmHint,
  AuthMethodInitialiseKey,
  AuthStrategyInputKey,
  AuthStrategyInputMode,
  LevelOfAssurance,
} from "@lindorm-io/common-types";

export type AuthenticationStrategyConfig = {
  method: AuthenticationMethod;
  strategy: AuthenticationStrategy;
  amrValuesMax: number;
  amrValuesMin: number;
  confirmKey: AuthStrategyInputKey;
  confirmLength: number | null;
  confirmMode: AuthStrategyInputMode;
  hint: AuthMethodConfirmHint;
  initialiseKey: AuthMethodInitialiseKey;
  mfaCookie: boolean;
  pollingRequired: boolean;
  tokenReturn: boolean;
  value: LevelOfAssurance;
  valueMax: LevelOfAssurance;
  weight: number;
};

export const AUTHENTICATION_STRATEGY_CONFIG: Array<AuthenticationStrategyConfig> = [
  {
    method: AuthenticationMethods.BANK_ID_SE,
    strategy: AuthenticationStrategies.BANK_ID_SE,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "none",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    value: 4,
    valueMax: 4,
    weight: 90,
  },
  {
    method: AuthenticationMethods.DEVICE_LINK,
    strategy: AuthenticationStrategies.DEVICE_CHALLENGE,
    amrValuesMax: 0,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "challenge_confirmation_token",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: true,
    value: 3,
    valueMax: 3,
    weight: 90,
  },
  {
    method: AuthenticationMethods.EMAIL,
    strategy: AuthenticationStrategies.EMAIL_LINK,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "email",
    confirmKey: "code",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: false,
    value: 2,
    valueMax: 2,
    weight: 10,
  },
  {
    method: AuthenticationMethods.EMAIL,
    strategy: AuthenticationStrategies.EMAIL_OTP,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "email",
    confirmKey: "otp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 2,
    weight: 30,
  },
  {
    method: AuthenticationMethods.MFA_COOKIE,
    strategy: AuthenticationStrategies.MFA_COOKIE,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "none",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 3,
    weight: 999,
  },
  {
    method: AuthenticationMethods.PASSWORD,
    strategy: AuthenticationStrategies.PASSWORD,
    amrValuesMax: 0,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "username",
    confirmKey: "password",
    confirmLength: null,
    confirmMode: "text",
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 3,
    weight: 10,
  },
  {
    method: AuthenticationMethods.PASSWORD,
    strategy: AuthenticationStrategies.PASSWORD_BROWSER_LINK,
    amrValuesMax: 0,
    amrValuesMin: 0,
    hint: "email",
    initialiseKey: "username",
    confirmKey: "password",
    confirmLength: null,
    confirmMode: "text",
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 3,
    valueMax: 3,
    weight: 20,
  },
  {
    method: AuthenticationMethods.PHONE,
    strategy: AuthenticationStrategies.PHONE_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "phone",
    initialiseKey: "phone_number",
    confirmKey: "otp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 10,
  },
  {
    method: AuthenticationMethods.DEVICE_LINK,
    strategy: AuthenticationStrategies.RDC_PUSH_NOTIFICATION,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "challenge_confirmation_token",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 3,
    weight: 90,
  },
  {
    method: AuthenticationMethods.DEVICE_LINK,
    strategy: AuthenticationStrategies.RDC_QR_CODE,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "challenge_confirmation_token",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 3,
    weight: 90,
  },
  {
    method: AuthenticationMethods.SESSION_LINK,
    strategy: AuthenticationStrategies.SESSION_ACCEPT_WITH_CODE,
    amrValuesMax: 1,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "code",
    confirmLength: 8,
    confirmMode: "text",
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 2,
    weight: 80,
  },
  {
    method: AuthenticationMethods.SESSION_LINK,
    strategy: AuthenticationStrategies.SESSION_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "otp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 80,
  },
  {
    method: AuthenticationMethods.TIME_BASED_OTP,
    strategy: AuthenticationStrategies.TIME_BASED_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "totp",
    confirmLength: 6,
    confirmMode: "numeric",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 90,
  },
  {
    method: AuthenticationMethods.WEBAUTHN,
    strategy: AuthenticationStrategies.WEBAUTHN,
    amrValuesMax: 9,
    amrValuesMin: 0,
    hint: "none",
    initialiseKey: "none",
    confirmKey: "none",
    confirmLength: null,
    confirmMode: "none",
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 90,
  },
];
