import { FlowType } from "../enum";
import { LevelOfAssurance } from "../common";

export interface FlowTypeConfig {
  name: FlowType;
  amrValuesMax: number;
  amrValuesMin: number;
  mfaCookie: boolean;
  pollingRequired: boolean;
  weight: number;
  tokenReturn: boolean;
  value: LevelOfAssurance;
  valueMax: LevelOfAssurance;
}

export const FLOW_TYPE_CONFIG: Array<FlowTypeConfig> = [
  {
    name: FlowType.BANK_ID_SE,
    amrValuesMax: 9,
    amrValuesMin: 0,
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    value: 4,
    valueMax: 4,
    weight: 90,
  },
  {
    name: FlowType.DEVICE_CHALLENGE,
    amrValuesMax: 0,
    amrValuesMin: 0,
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: true,
    value: 3,
    valueMax: 3,
    weight: 90,
  },
  {
    name: FlowType.EMAIL_LINK,
    amrValuesMax: 9,
    amrValuesMin: 0,
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: false,
    value: 2,
    valueMax: 2,
    weight: 10,
  },
  {
    name: FlowType.EMAIL_OTP,
    amrValuesMax: 9,
    amrValuesMin: 0,
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: false,
    value: 2,
    valueMax: 2,
    weight: 20,
  },
  {
    name: FlowType.MFA_COOKIE,
    amrValuesMax: 9,
    amrValuesMin: 1,
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 3,
    weight: 999,
  },
  {
    name: FlowType.PASSWORD,
    amrValuesMax: 0,
    amrValuesMin: 0,
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 2,
    valueMax: 3,
    weight: 10,
  },
  {
    name: FlowType.PASSWORD_BROWSER_LINK,
    amrValuesMax: 0,
    amrValuesMin: 0,
    mfaCookie: false,
    pollingRequired: false,
    tokenReturn: true,
    value: 3,
    valueMax: 3,
    weight: 20,
  },
  {
    name: FlowType.PHONE_OTP,
    amrValuesMax: 9,
    amrValuesMin: 0,
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 20,
  },
  {
    name: FlowType.RDC_QR_CODE,
    amrValuesMax: 9,
    amrValuesMin: 0,
    mfaCookie: true,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 3,
    weight: 90,
  },
  {
    name: FlowType.SESSION_ACCEPT_WITH_CODE,
    amrValuesMax: 1,
    amrValuesMin: 0,
    mfaCookie: false,
    pollingRequired: true,
    tokenReturn: false,
    valueMax: 3,
    value: 2,
    weight: 80,
  },
  {
    name: FlowType.SESSION_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 80,
  },
  {
    name: FlowType.TIME_BASED_OTP,
    amrValuesMax: 9,
    amrValuesMin: 1,
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 90,
  },
  {
    name: FlowType.WEBAUTHN,
    amrValuesMax: 9,
    amrValuesMin: 0,
    mfaCookie: true,
    pollingRequired: false,
    tokenReturn: true,
    valueMax: 3,
    value: 2,
    weight: 90,
  },
];
